
NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

In [2]:
import numpy as np

# Creating a 1-dimensional array from a list
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1)

# Creating a 2-dimensional array (matrix) from a list of lists
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr2)


1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]


In [3]:
# Basic arithmetic operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)
print("a * b =", a * b)

# Statistical operations
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMean along axis 0:", np.mean(arr, axis=0))
print("Standard deviation along axis 1:", np.std(arr, axis=1))


a + b = [5 7 9]
a * b = [ 4 10 18]

Mean along axis 0: [2.5 3.5 4.5]
Standard deviation along axis 1: [0.81649658 0.81649658]


In [4]:
# Broadcasting example
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

print("a + b (broadcasting):")
print(a + b)


a + b (broadcasting):
[[11 22 33]
 [14 25 36]]


In [5]:
# Indexing and slicing
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Element at (0, 1):", arr[0, 1])
print("First row:", arr[0, :])
print("Last column:", arr[:, -1])


Element at (0, 1): 2
First row: [1 2 3]
Last column: [3 6 9]
